//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Hospital_DbEntities : DbContext
    {
        public Hospital_DbEntities()
            : base("name=Hospital_DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Card_Types> Card_Types { get; set; }
        public virtual DbSet<Marital_Statuses> Marital_Statuses { get; set; }
        public virtual DbSet<Next_of_kins> Next_of_kins { get; set; }
        public virtual DbSet<Occupation> Occupations { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Religion> Religions { get; set; }
        public virtual DbSet<State_of_origins> State_of_origins { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
    }
}
