//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int Id { get; set; }
        public int Patient_title_id { get; set; }
        public string Patient_firstname { get; set; }
        public string Patient_middlename { get; set; }
        public string Patient_surname { get; set; }
        public string Patient_gender { get; set; }
        public int Patient_marital_status_id { get; set; }
        public System.DateTime Patient_dateof_birth { get; set; }
        public int Patient_stateof_origin_id { get; set; }
        public string Patient_tribe { get; set; }
        public int Patient_religion_id { get; set; }
        public int Patient_occupation_id { get; set; }
        public string Patient_permanent_address { get; set; }
        public string Patient_home_address { get; set; }
        public string Patient_phone { get; set; }
        public int Patient_relation_id { get; set; }
        public int Patient_account_no { get; set; }
        public string Patient_photo { get; set; }
        public string Patient_file { get; set; }
        public int Patient_card_type_id { get; set; }
        public bool Patient_status { get; set; }
    
        public virtual Card_Types Card_Types { get; set; }
        public virtual Marital_Statuses Marital_Statuses { get; set; }
        public virtual Occupation Occupation { get; set; }
        public virtual State_of_origins State_of_origins { get; set; }
        public virtual Religion Religion { get; set; }
        public virtual Title Title { get; set; }
    }
}
